### PR TITLE
Attempting to load invalid JSON in body raises exception 

### PR DESCRIPTION
**Pull request by andyfase**
This change catches the exception when invalid JSON is provided to `json.loads` the `or "{}"` that was in the code after `json.loads` didn't actually do anything, as the JSON libarary raises an expection vs return . I believe this change moves the functionality to expected behaviour i.e. if the JSON fails to load then an empty dictionary is the result.

### CODE REVIEW

**Comment by sloev** [comment]
@andyfase i think we need to be explicit when failing on loading incoming json data and failing on it, especially when the handler deliberatly has chosen to "load_json": https://github.com/sloev/python-lambdarest/blob/master/lambdarest/__init__.py#L365

i suggest we instead raise a custom malformed_json_error

that we then can catch here: https://github.com/sloev/python-lambdarest/blob/master/lambdarest/__init__.py#L325
and return a proper bad-request-400 response

cause if the handler expects json and is given a body that cant be loaded then client should know i think :-)

**Comment by andyfase** [comment]
Yes your right - I missed that you can pass in `load_json=False` in the decorator. I was just confused by the `or {}` statement. Ok let me rework this and update the PR.

**Comment by sloev** [comment]
@andyfase sweet, looking forward to it!!!
:-) thanks!

**Comment by sloev** [comment]
@andyfase i'm gonna close down this pr if no new content last 20 days :-)

**Pull request closed without merging**
